version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eForm
    versions:
    - 4.3.10
    - 4.3.11
    - 4.3.12
    - 4.3.14
    - 4.3.15
    - 4.3.16
    - 4.3.17
    - 4.3.18
    - 4.3.4
    - 4.3.8
    - 4.3.9
    - 4.4.1
    - 4.4.11
    - 4.4.13
    - 4.4.14
    - 4.4.17
    - 4.4.19
    - 4.4.2
    - 4.4.20
    - 4.4.22
    - 4.4.24
    - 4.4.26
    - 4.4.27
    - 4.4.3
    - 4.4.31
    - 4.4.35
    - 4.4.36
    - 4.4.37
    - 4.4.4
    - 4.4.6
    - 4.4.7
    - 4.4.9
    - 4.5.0
    - 4.5.2
