// <auto-generated />
namespace HistorySql
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingResetValuesFieldId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingResetValuesFieldId));
        
        string IMigrationMetadata.Id
        {
            get { return "201810051211468_AddingResetValuesFieldId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
